### ISSUE TITLE
mongo-edit doesn't work in windows

### ISSUE THREAD

**Issue by guoxiangyang** [louischatriot/mongo-edit#15]
hi, mongo-edit is very light & useful. I like it.

I've used it in osx, ubuntu, it works well. but in windows, when click collection name in the left, the right detail page doesn't show.

I've track the code, data was loaded from MongoDB, problem is in render process. the render only return the left part of the page. h4e is more complicate & I have no time to get in it.

**Comment by louischatriot** [comment]
Thanks :) I modified mongo edit so that it uses the latest version of h4e. I'm not sure this will solve the problem but I don't have access to a Windows machine right now so try to `git pull` the code and tell me if the problem persists. If it does I will try to solve it next week.

**Comment by louischatriot** [comment]
The fix to h4e should have solved your problem, please get back to me if it didn't.

**Comment by nullpotent** [comment]
The problem persists. I've encountered it on 2 Windows 7 and 1 Win8 machines.
