### ISSUE TITLE
default configs when embedding mongo-edit as an app

### ISSUE THREAD

**Issue by seanmiddleditch** [louischatriot/mongo-edit#17]
For convenience during the very early stages of a new project, I tried to bind mongo-edit as an app in Express after installing it via npm.  Unfortunately the default configuration does not use install-relateive paths for things like templatesDir so it fails.

Reproduce steps:
1) in shell:
   npm install mongo-edit
2) in myapp.js
  var express = require('express');
  express().use('/mongo-edit', require('mongo-edit')).listen(8080);

Errors:
Error: ENOENT, no such file or directory '/home/elanthis/webmud/templates'
    at Object.fs.readdirSync (fs.js:654:18)
    at readAndCompileTemplates (/home/elanthis/webmud/node_modules/mongo-edit/node_modules/h4e/index.js:27:14)
    at /home/elanthis/webmud/node_modules/mongo-edit/node_modules/h4e/index.js:98:39
    at Array.forEach (native)
    at Function._.each._.forEach (/home/elanthis/webmud/node_modules/mongo-edit/node_modules/h4e/node_modules/underscore/underscore.js:79:11)
    at Object.setup (/home/elanthis/webmud/node_modules/mongo-edit/node_modules/h4e/index.js:98:5)

I believe a few relatively minor changes to how the default config and urls are generated should make this situation work perfectly, and it would be quite handy for those who have strong desire/need to run everything off a single port (say, when a development server is behind a firewall with only one open port).

**Comment by louischatriot** [comment]
Hello,

I see how this would be helpful, but I don't have time to code on Mongo Edit these days (too much work on NeDB - https://github.com/louischatriot/nedb). If you can submit a PR on this, I'll make sure to review and merge it though. I'll close this issue in the meantime.

Cheers,
Louis
